<?php
/**
 * Copyright (c) 2017-2020 David J Bullock
 * Web Power and Light, LLC
 * https://webpowerandlight.com
 * support@webpowerandlight.com
 *
 */

 if (!defined('ABSPATH' ) ) { die(); } echo '<form method="POST" action="">'; wp_nonce_field(MEMBERIUM_LIB, 'memberium_options_nonce' ); $vwpalm4is_n35udsrb2hz = get_option('memberium_extensions', array() ); $vwpalm4is_zwkue0 = wpalm4is_adxa8oln(); $vwpalm4is_w1katprd = array(); $vwpalm4is_ne17fdv8uw4 = wpalm4is_xb7t0i6pzn::wpalm4is_s0xuab5fq6hy('settings'); foreach($vwpalm4is_n35udsrb2hz as $vwpalm4is_ndxvp20 => $vwpalm4is_x1folrs) { if (! array_key_exists($vwpalm4is_ndxvp20, $vwpalm4is_zwkue0) ) { unset($vwpalm4is_n35udsrb2hz[$vwpalm4is_ndxvp20]); } } ksort($vwpalm4is_n35udsrb2hz); foreach($vwpalm4is_zwkue0 as $vwpalm4is_vnz9uf => $vwpalm4is_h715p_v) { $vwpalm4is_rs76aqhfcu5z = dirname(MEMBERIUM_LIB . $vwpalm4is_h715p_v) . '/info.txt'; if (file_exists($vwpalm4is_rs76aqhfcu5z) ) { $vwpalm4is_w1katprd[] = $vwpalm4is_rs76aqhfcu5z; } } echo '<ul>'; echo '<h3>Optional Extensions</h3>'; foreach ($vwpalm4is_w1katprd as $vwpalm4is_kh4_803ao => $vwpalm4is_h715p_v ) { $vwpalm4is_kdyhkpef1bo = dirname($vwpalm4is_h715p_v) . '/info.txt'; $vwpalm4is_n0wrho_2u = get_plugin_data($vwpalm4is_kdyhkpef1bo, false, false ); $vwpalm4is_q1uwte_ = basename(dirname($vwpalm4is_h715p_v) ); $vwpalm4is_ug8xs2q3 = isset($vwpalm4is_n35udsrb2hz[$vwpalm4is_q1uwte_] ) ? $vwpalm4is_n35udsrb2hz[$vwpalm4is_q1uwte_] : 1; if (! empty($vwpalm4is_n0wrho_2u['Name'] ) ) { echo wpalm4is_yf0g75hqk184::wpalm4is_ak_b1tzs8($vwpalm4is_n0wrho_2u['Name'], "extensions[{$vwpalm4is_q1uwte_}]", $vwpalm4is_n0wrho_2u['AuthorURI'], (bool) $vwpalm4is_ug8xs2q3 ); } } echo '</ul>'; echo '<ul>'; echo '<h3>Optional Settings</h3>'; wpalm4is_yf0g75hqk184::wpalm4is_kufeh2i6jmg4( 'Facebook App ID', 'facebook_app_id', $vwpalm4is_ne17fdv8uw4['facebook_app_id'], array('help_id' => 2571, 'style' => 'text-align:left;width:100px;' ) ); wpalm4is_yf0g75hqk184::wpalm4is_kufeh2i6jmg4( 'Spiffy Subdomain', 'spiffy_subdomain', $vwpalm4is_ne17fdv8uw4['spiffy_subdomain'], array( 'help_id' => 0000, 'pattern' => '[A-Za-z0-9][A-Za-z0-9\-]+', 'style' => 'text-align:left;width:100px;', 'placeholder' => 'Enter your Spiffy Subdomain here', ) ); echo '</ul>'; echo '<p><input type="submit" value="Update" class="button-primary"></p>'; echo '</form>';
