<?php
/**
 * Copyright (c) 2018-2020 David J Bullock
 * Web Power and Light, LLC
 * https://webpowerandlight.com
 * support@webpowerandlight.com
 *
 */

 if (!defined('ABSPATH') ) { die(); } final class wpalm4is_aznwrha4 { static function wpalm4is_iirgtfjk6h() { static $vwpalm4is_f7hukoe3m0 = NULL; if (! empty($vwpalm4is_f7hukoe3m0) ) { return $vwpalm4is_f7hukoe3m0; } $vwpalm4is_f7hukoe3m0 = $_SERVER['REMOTE_ADDR']; $vwpalm4is_ru9c284hab = array( 'HTTP_CLIENT_IP', 'HTTP_X_FORWARDED_FOR', 'HTTP_X_FORWARDED', 'HTTP_X_CLUSTER_CLIENT_IP', 'HTTP_FORWARDED_FOR', 'HTTP_FORWARDED', ); foreach ($vwpalm4is_ru9c284hab as $vwpalm4is_x3e6m_hobj) { if (array_key_exists($vwpalm4is_x3e6m_hobj, $_SERVER) === true) { foreach (explode(',', $_SERVER[$vwpalm4is_x3e6m_hobj]) as $vwpalm4is_xkij4m) { $vwpalm4is_xkij4m = trim($vwpalm4is_xkij4m); if (self::wpalm4is_p1dt7ge($vwpalm4is_xkij4m) ) { $vwpalm4is_f7hukoe3m0 = $vwpalm4is_xkij4m; } } } } return $vwpalm4is_f7hukoe3m0; } private static function wpalm4is_p1dt7ge($vwpalm4is_xkij4m) { if (filter_var($vwpalm4is_xkij4m, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 | FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) === false) { return false; } return true; } static function wpalm4is__f2a8q($vwpalm4is_sf9tqcp3 = '', $vwpalm4is_k_u65qtp7 = false, $vwpalm4is_g87myl0d = null) { $vwpalm4is_vx_n8e7hdrbo = array( 'timeout' => 3, ); $vwpalm4is_g87myl0d = wp_parse_args($vwpalm4is_g87myl0d, $vwpalm4is_vx_n8e7hdrbo); $vwpalm4is_zi96wnzyh0o = wp_remote_get($vwpalm4is_sf9tqcp3, $vwpalm4is_g87myl0d); if (is_array($vwpalm4is_zi96wnzyh0o) ) { if (empty($vwpalm4is_zi96wnzyh0o['body']) ) { $vwpalm4is_zi96wnzyh0o['body'] = ''; } if (! $vwpalm4is_k_u65qtp7) { return $vwpalm4is_zi96wnzyh0o['body']; } else { return $vwpalm4is_zi96wnzyh0o; } } else { return false; } return; } static function wpalm4is_nkf7lr9bncq($vwpalm4is_xkij4m, $vwpalm4is_mis2lqx) { list($subnet, $vwpalm4is_k9i_ho) = explode('/', $vwpalm4is_mis2lqx); if ( (ip2long($vwpalm4is_xkij4m) & ~( (1 << (32 - $vwpalm4is_k9i_ho) ) - 1) ) == ip2long($subnet) ) { return true; } return false; } static function wpalm4is_ke5aldq() { $vwpalm4is_ql0mb4js6 = 'memberium/aws_subnets'; $vwpalm4is_dd3f67m = get_transient($vwpalm4is_ql0mb4js6); if ($vwpalm4is_dd3f67m === false) {  $vwpalm4is_zi96wnzyh0o = wp_remote_get('https://ip-ranges.amazonaws.com/ip-ranges.json');  $vwpalm4is_zi96wnzyh0o = json_decode($vwpalm4is_zi96wnzyh0o['body']); $vwpalm4is_dd3f67m = $vwpalm4is_zi96wnzyh0o->prefixes; set_transient($vwpalm4is_ql0mb4js6, $vwpalm4is_dd3f67m, 24 * HOUR_IN_SECONDS); unset($vwpalm4is_zi96wnzyh0o); } return $vwpalm4is_dd3f67m; } static function wpalm4is_lb25fxh() { $vwpalm4is_dd3f67m = wpalm4is_aznwrha4::wpalm4is_ke5aldq(); $vwpalm4is_qknt5yz = array(); foreach($vwpalm4is_dd3f67m as $vwpalm4is_ucg8isr) { if ('S3' == $vwpalm4is_ucg8isr->service) { $vwpalm4is_qknt5yz[$vwpalm4is_ucg8isr->region] = $vwpalm4is_ucg8isr->region; } } ksort($vwpalm4is_qknt5yz); return $vwpalm4is_qknt5yz; } }
